language:
  python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.5.11
install:
  - export PYTHONPATH=$PYTHONPATH:./imagestore/
  - pip install Django==$DJANGO --use-mirrors
  - pip install -r test/testapp/requirements.txt
script:
  - python test/testapp/manage.py test imagestore
